### PR TITLE
D lookup am bezier

### PR DESCRIPTION
**Pull request by jamitch-snl**
Add new am bezier model app.  

- new app and associated source files (7 new files, 1 modified existing file 'am_raster')
- app docs
- examples

This model also includes the calculation of a static table of distances within the haz that move along with melt pool.

### CODE REVIEW

**Comment by sjplimp** [comment]
@jamitch - 2 quick comments
(1) the new app needs to be added to the Section_comands.txt file at the end in the table of applications
(2) not clear why the new app-specific command is called potts/am/bezier instead of "am bezier" like
      the 6 others: "am build", "am pass, am path, etc ??   just looking for consistency - I don't think we
      have any other commands (top level) with slashes in them

**Comment by jamitch-snl** [comment]
@sjplimp Thanks Steve.  

- Yeah I forgot about the Section_comands.txt command.  Will do.
- Ok on the potts/am/bezier command -- I'll need to look and make sure it doesn't break something else. -- but nice thing about that naming convention is that the command is only applicable to the app_style  potts/am/bezier. -- so it matches with the app.  I think you objected to the same thing a year or so ago on another app. I'll investigate this.

**Comment by jamitch-snl** [comment]
@sjplimp 
There is a command which uses a slash.  See the diffusion/multiphase command.  So its not unprecedented:)  I like this approach because it links and designates the command to a specific app.  For instance the 'diffusion/multiphase' command goes with app_style diffusion/multiphase.  We had this same discussion last year when we released the app_style diffusion/multiphase app.  

Commands like 'am build', 'am pass', 'am path' etc are all related to rastering.  There is not a logical/easy way to parse the bezier control points with the same mechanism because the input needs to go to the derived class in this case.   I could modify the command to something like 'am_bezier' -- note there is an underscore.  But I prefer the existing now that I have reminded myself. Can you give this another look?

**Comment by sjplimp** [comment]
@jamitch-snl 
ok - I had forgotten about our previous discussion - makes sense now - potts/am/bezier is fine for the new command.
Are you saying this is only applicable to app potts/am/bezier?  Not to other AM related apps?

Maybe the convention should be that command like "temperature" which applies to multiple apps should
have its own name, but a command that applies to only one app should prepend the app name?
We could change that later in another PR.

**Review by sjplimp — APPROVED** [review]

**Comment by jamitch-snl** [comment]
@sjplimp Thanks Steve.
Yes -- potts/am/bezier commands are only applicable to the app_style potts/am/bezier app.  Similar goes for the diffusion/multiphase per discussion.  It is a rather nice convention.  Right -- temperature is a much broader command that many apps may use and as you pointed out it already fits the convention.  I'm not sure how many apps define commands which are only applicable to them.  It is a really nice convention to follow and probably wouldn't be that much to sort through.  The am commands are kind of special and probably don't fit this exactly but they are close in spirit.

**Pull request merged**
