### PR TITLE
Update version to 6 Sep 2023 in preparation for release

### PR DESCRIPTION
**Pull request by jamitch-snl**
Thanks Steve.  Here are list of things we need to do -- I can do some of these.  

- mpi stub out MPIalltoallv 
- Update publications and replace 'no mans land paper' with new 'spparks' paper
- Update txt files to point at spparks.github.io rather than spparks.sandia.gov 
- Update developers (manual.txt, authors.txt)

### CODE REVIEW

**Comment by sjplimp** [comment]
@jamitch I added the MPI stub, can you run the code for that in serial and verify it works ?
I also updated the txt files for the manual with links to the GitHub website
I also edited the doc page Manual.txt with info on developers
I think the other changes you list are for the website, not the SPPARKS code repo

**Comment by sjplimp** [comment]
@jamitch-snl So if the MPI Alltoallv test passes, I think this is ready to merge for a new release - then we can update the doc pages

**Comment by jamitch-snl** [comment]
@sjplimp 
Standby.. I'm working on it.  Build is having a link error.  It may be my makefile.

**Comment by jamitch-snl** [comment]
@sjplimp 
The new STUBS worked -- at least the build did anyway.  Lets proceed.

**Pull request merged**
