### PR TITLE
Add SPPARKS version info to continued logfiles specified by input script log command

### PR DESCRIPTION
**Pull request by sjplimp**
Add SPPARKS versions and a "continued" message to new log files which are created by the log command.
Also fix a logfile name error in the log command doc page.

### CODE REVIEW

**Comment by sjplimp** [comment]
@jamitch-snl Please try this out and see if it is what you want.

**Comment by jamitch-snl** [comment]
@sjplimp Looks good.  I ran examples/in.potts; I like the '-- continued logfile from same input script' bit. 

I'm good with this.  Is this branch ready to merge or do you have other stuff your planning to put in this branch?

**Review by jamitch-snl — COMMENTED** [review]
Looks good. I ran examples/in.potts; I like the '-- continued logfile from same input script' bit.

I'm good with this. Is this branch ready to merge or do you have other stuff your planning to put in this branch?

**Comment by sjplimp** [comment]
it's ready to merge

**Pull request merged**
